// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apps.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppMetric = `-- name: CreateAppMetric :exec
INSERT INTO app_metrics (
    app_id, cpu_pct, mem_bytes, mem_limit_bytes,
    net_rx_bytes, net_tx_bytes, req_rate, err_rate, p50_ms, p95_ms
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type CreateAppMetricParams struct {
	AppID         pgtype.UUID
	CpuPct        float64
	MemBytes      int64
	MemLimitBytes int64
	NetRxBytes    int64
	NetTxBytes    int64
	ReqRate       float64
	ErrRate       float64
	P50Ms         float64
	P95Ms         float64
}

func (q *Queries) CreateAppMetric(ctx context.Context, arg CreateAppMetricParams) error {
	_, err := q.db.Exec(ctx, createAppMetric,
		arg.AppID,
		arg.CpuPct,
		arg.MemBytes,
		arg.MemLimitBytes,
		arg.NetRxBytes,
		arg.NetTxBytes,
		arg.ReqRate,
		arg.ErrRate,
		arg.P50Ms,
		arg.P95Ms,
	)
	return err
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
    org_id, name, slug, source_type, builder, git_repo_url, git_branch, image_ref,
    registry_creds_enc, exposed_port, healthcheck_path, auto_deploy,
    build_context, dockerfile_path, build_args, mem_limit, cpu_limit, pids_limit,
    notify_on_success, deploy_strategy, compose_path, compose_service
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22)
RETURNING id, org_id, name, slug, source_type, builder, git_repo_url, git_branch, image_ref, registry_creds_enc, exposed_port, healthcheck_path, auto_deploy, build_context, dockerfile_path, build_args, key_version, created_at, updated_at, desired_state, mem_limit, cpu_limit, pids_limit, notify_on_success, deploy_strategy, compose_path, compose_service
`

type CreateApplicationParams struct {
	OrgID            pgtype.UUID
	Name             string
	Slug             string
	SourceType       string
	Builder          string
	GitRepoUrl       string
	GitBranch        string
	ImageRef         string
	RegistryCredsEnc []byte
	ExposedPort      int32
	HealthcheckPath  string
	AutoDeploy       bool
	BuildContext     string
	DockerfilePath   string
	BuildArgs        []byte
	MemLimit         pgtype.Text
	CpuLimit         pgtype.Text
	PidsLimit        pgtype.Int4
	NotifyOnSuccess  bool
	DeployStrategy   pgtype.Text
	ComposePath      string
	ComposeService   string
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.OrgID,
		arg.Name,
		arg.Slug,
		arg.SourceType,
		arg.Builder,
		arg.GitRepoUrl,
		arg.GitBranch,
		arg.ImageRef,
		arg.RegistryCredsEnc,
		arg.ExposedPort,
		arg.HealthcheckPath,
		arg.AutoDeploy,
		arg.BuildContext,
		arg.DockerfilePath,
		arg.BuildArgs,
		arg.MemLimit,
		arg.CpuLimit,
		arg.PidsLimit,
		arg.NotifyOnSuccess,
		arg.DeployStrategy,
		arg.ComposePath,
		arg.ComposeService,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.SourceType,
		&i.Builder,
		&i.GitRepoUrl,
		&i.GitBranch,
		&i.ImageRef,
		&i.RegistryCredsEnc,
		&i.ExposedPort,
		&i.HealthcheckPath,
		&i.AutoDeploy,
		&i.BuildContext,
		&i.DockerfilePath,
		&i.BuildArgs,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DesiredState,
		&i.MemLimit,
		&i.CpuLimit,
		&i.PidsLimit,
		&i.NotifyOnSuccess,
		&i.DeployStrategy,
		&i.ComposePath,
		&i.ComposeService,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplication, id)
	return err
}

const getApplication = `-- name: GetApplication :one
SELECT id, org_id, name, slug, source_type, builder, git_repo_url, git_branch, image_ref, registry_creds_enc, exposed_port, healthcheck_path, auto_deploy, build_context, dockerfile_path, build_args, key_version, created_at, updated_at, desired_state, mem_limit, cpu_limit, pids_limit, notify_on_success, deploy_strategy, compose_path, compose_service FROM applications WHERE id = $1
`

func (q *Queries) GetApplication(ctx context.Context, id pgtype.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.SourceType,
		&i.Builder,
		&i.GitRepoUrl,
		&i.GitBranch,
		&i.ImageRef,
		&i.RegistryCredsEnc,
		&i.ExposedPort,
		&i.HealthcheckPath,
		&i.AutoDeploy,
		&i.BuildContext,
		&i.DockerfilePath,
		&i.BuildArgs,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DesiredState,
		&i.MemLimit,
		&i.CpuLimit,
		&i.PidsLimit,
		&i.NotifyOnSuccess,
		&i.DeployStrategy,
		&i.ComposePath,
		&i.ComposeService,
	)
	return i, err
}

const latestAppMetric = `-- name: LatestAppMetric :one
SELECT app_id, created_at, cpu_pct, mem_bytes, mem_limit_bytes, net_rx_bytes, net_tx_bytes, req_rate, err_rate, p50_ms, p95_ms FROM app_metrics
WHERE app_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) LatestAppMetric(ctx context.Context, appID pgtype.UUID) (AppMetric, error) {
	row := q.db.QueryRow(ctx, latestAppMetric, appID)
	var i AppMetric
	err := row.Scan(
		&i.AppID,
		&i.CreatedAt,
		&i.CpuPct,
		&i.MemBytes,
		&i.MemLimitBytes,
		&i.NetRxBytes,
		&i.NetTxBytes,
		&i.ReqRate,
		&i.ErrRate,
		&i.P50Ms,
		&i.P95Ms,
	)
	return i, err
}

const listAllAppIDs = `-- name: ListAllAppIDs :many
SELECT id, slug FROM applications
`

type ListAllAppIDsRow struct {
	ID   pgtype.UUID
	Slug string
}

func (q *Queries) ListAllAppIDs(ctx context.Context) ([]ListAllAppIDsRow, error) {
	rows, err := q.db.Query(ctx, listAllAppIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllAppIDsRow
	for rows.Next() {
		var i ListAllAppIDsRow
		if err := rows.Scan(&i.ID, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppMetricsSince = `-- name: ListAppMetricsSince :many
SELECT app_id, created_at, cpu_pct, mem_bytes, mem_limit_bytes, net_rx_bytes, net_tx_bytes, req_rate, err_rate, p50_ms, p95_ms FROM app_metrics
WHERE app_id = $1 AND created_at >= $2
ORDER BY created_at
`

type ListAppMetricsSinceParams struct {
	AppID     pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListAppMetricsSince(ctx context.Context, arg ListAppMetricsSinceParams) ([]AppMetric, error) {
	rows, err := q.db.Query(ctx, listAppMetricsSince, arg.AppID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppMetric
	for rows.Next() {
		var i AppMetric
		if err := rows.Scan(
			&i.AppID,
			&i.CreatedAt,
			&i.CpuPct,
			&i.MemBytes,
			&i.MemLimitBytes,
			&i.NetRxBytes,
			&i.NetTxBytes,
			&i.ReqRate,
			&i.ErrRate,
			&i.P50Ms,
			&i.P95Ms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsForOrg = `-- name: ListApplicationsForOrg :many
SELECT id, org_id, name, slug, source_type, builder, git_repo_url, git_branch, image_ref, registry_creds_enc, exposed_port, healthcheck_path, auto_deploy, build_context, dockerfile_path, build_args, key_version, created_at, updated_at, desired_state, mem_limit, cpu_limit, pids_limit, notify_on_success, deploy_strategy, compose_path, compose_service FROM applications WHERE org_id = $1 ORDER BY created_at
`

func (q *Queries) ListApplicationsForOrg(ctx context.Context, orgID pgtype.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.SourceType,
			&i.Builder,
			&i.GitRepoUrl,
			&i.GitBranch,
			&i.ImageRef,
			&i.RegistryCredsEnc,
			&i.ExposedPort,
			&i.HealthcheckPath,
			&i.AutoDeploy,
			&i.BuildContext,
			&i.DockerfilePath,
			&i.BuildArgs,
			&i.KeyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DesiredState,
			&i.MemLimit,
			&i.CpuLimit,
			&i.PidsLimit,
			&i.NotifyOnSuccess,
			&i.DeployStrategy,
			&i.ComposePath,
			&i.ComposeService,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitAppsByBranch = `-- name: ListGitAppsByBranch :many
SELECT id, org_id, name, slug, source_type, builder, git_repo_url, git_branch, image_ref, registry_creds_enc, exposed_port, healthcheck_path, auto_deploy, build_context, dockerfile_path, build_args, key_version, created_at, updated_at, desired_state, mem_limit, cpu_limit, pids_limit, notify_on_success, deploy_strategy, compose_path, compose_service FROM applications WHERE source_type = 'git' AND git_branch = $1
`

func (q *Queries) ListGitAppsByBranch(ctx context.Context, gitBranch string) ([]Application, error) {
	rows, err := q.db.Query(ctx, listGitAppsByBranch, gitBranch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.SourceType,
			&i.Builder,
			&i.GitRepoUrl,
			&i.GitBranch,
			&i.ImageRef,
			&i.RegistryCredsEnc,
			&i.ExposedPort,
			&i.HealthcheckPath,
			&i.AutoDeploy,
			&i.BuildContext,
			&i.DockerfilePath,
			&i.BuildArgs,
			&i.KeyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DesiredState,
			&i.MemLimit,
			&i.CpuLimit,
			&i.PidsLimit,
			&i.NotifyOnSuccess,
			&i.DeployStrategy,
			&i.ComposePath,
			&i.ComposeService,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAppMetrics = `-- name: PurgeAppMetrics :execrows
DELETE FROM app_metrics WHERE created_at < now() - interval '48 hours'
`

func (q *Queries) PurgeAppMetrics(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeAppMetrics)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setApplicationDesiredState = `-- name: SetApplicationDesiredState :one
UPDATE applications SET desired_state = $2, updated_at = now()
WHERE id = $1
RETURNING id, org_id, name, slug, source_type, builder, git_repo_url, git_branch, image_ref, registry_creds_enc, exposed_port, healthcheck_path, auto_deploy, build_context, dockerfile_path, build_args, key_version, created_at, updated_at, desired_state, mem_limit, cpu_limit, pids_limit, notify_on_success, deploy_strategy, compose_path, compose_service
`

type SetApplicationDesiredStateParams struct {
	ID           pgtype.UUID
	DesiredState string
}

func (q *Queries) SetApplicationDesiredState(ctx context.Context, arg SetApplicationDesiredStateParams) (Application, error) {
	row := q.db.QueryRow(ctx, setApplicationDesiredState, arg.ID, arg.DesiredState)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.SourceType,
		&i.Builder,
		&i.GitRepoUrl,
		&i.GitBranch,
		&i.ImageRef,
		&i.RegistryCredsEnc,
		&i.ExposedPort,
		&i.HealthcheckPath,
		&i.AutoDeploy,
		&i.BuildContext,
		&i.DockerfilePath,
		&i.BuildArgs,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DesiredState,
		&i.MemLimit,
		&i.CpuLimit,
		&i.PidsLimit,
		&i.NotifyOnSuccess,
		&i.DeployStrategy,
		&i.ComposePath,
		&i.ComposeService,
	)
	return i, err
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications SET
    name = $2, builder = $3, git_branch = $4, image_ref = $5,
    exposed_port = $6, healthcheck_path = $7, auto_deploy = $8,
    build_context = $9, dockerfile_path = $10, build_args = $11,
    registry_creds_enc = $12, mem_limit = $13, cpu_limit = $14,
    pids_limit = $15, notify_on_success = $16, deploy_strategy = $17,
    compose_path = $18, compose_service = $19, updated_at = now()
WHERE id = $1
RETURNING id, org_id, name, slug, source_type, builder, git_repo_url, git_branch, image_ref, registry_creds_enc, exposed_port, healthcheck_path, auto_deploy, build_context, dockerfile_path, build_args, key_version, created_at, updated_at, desired_state, mem_limit, cpu_limit, pids_limit, notify_on_success, deploy_strategy, compose_path, compose_service
`

type UpdateApplicationParams struct {
	ID               pgtype.UUID
	Name             string
	Builder          string
	GitBranch        string
	ImageRef         string
	ExposedPort      int32
	HealthcheckPath  string
	AutoDeploy       bool
	BuildContext     string
	DockerfilePath   string
	BuildArgs        []byte
	RegistryCredsEnc []byte
	MemLimit         pgtype.Text
	CpuLimit         pgtype.Text
	PidsLimit        pgtype.Int4
	NotifyOnSuccess  bool
	DeployStrategy   pgtype.Text
	ComposePath      string
	ComposeService   string
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication,
		arg.ID,
		arg.Name,
		arg.Builder,
		arg.GitBranch,
		arg.ImageRef,
		arg.ExposedPort,
		arg.HealthcheckPath,
		arg.AutoDeploy,
		arg.BuildContext,
		arg.DockerfilePath,
		arg.BuildArgs,
		arg.RegistryCredsEnc,
		arg.MemLimit,
		arg.CpuLimit,
		arg.PidsLimit,
		arg.NotifyOnSuccess,
		arg.DeployStrategy,
		arg.ComposePath,
		arg.ComposeService,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.SourceType,
		&i.Builder,
		&i.GitRepoUrl,
		&i.GitBranch,
		&i.ImageRef,
		&i.RegistryCredsEnc,
		&i.ExposedPort,
		&i.HealthcheckPath,
		&i.AutoDeploy,
		&i.BuildContext,
		&i.DockerfilePath,
		&i.BuildArgs,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DesiredState,
		&i.MemLimit,
		&i.CpuLimit,
		&i.PidsLimit,
		&i.NotifyOnSuccess,
		&i.DeployStrategy,
		&i.ComposePath,
		&i.ComposeService,
	)
	return i, err
}
