// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apps.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
    org_id, name, slug, source_type, builder, git_repo_url, git_branch, image_ref,
    registry_creds_enc, exposed_port, healthcheck_path, auto_deploy,
    build_context, dockerfile_path, build_args
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
RETURNING id, org_id, name, slug, source_type, builder, git_repo_url, git_branch, image_ref, registry_creds_enc, exposed_port, healthcheck_path, auto_deploy, build_context, dockerfile_path, build_args, key_version, created_at, updated_at, desired_state
`

type CreateApplicationParams struct {
	OrgID            pgtype.UUID
	Name             string
	Slug             string
	SourceType       string
	Builder          string
	GitRepoUrl       string
	GitBranch        string
	ImageRef         string
	RegistryCredsEnc []byte
	ExposedPort      int32
	HealthcheckPath  string
	AutoDeploy       bool
	BuildContext     string
	DockerfilePath   string
	BuildArgs        []byte
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.OrgID,
		arg.Name,
		arg.Slug,
		arg.SourceType,
		arg.Builder,
		arg.GitRepoUrl,
		arg.GitBranch,
		arg.ImageRef,
		arg.RegistryCredsEnc,
		arg.ExposedPort,
		arg.HealthcheckPath,
		arg.AutoDeploy,
		arg.BuildContext,
		arg.DockerfilePath,
		arg.BuildArgs,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.SourceType,
		&i.Builder,
		&i.GitRepoUrl,
		&i.GitBranch,
		&i.ImageRef,
		&i.RegistryCredsEnc,
		&i.ExposedPort,
		&i.HealthcheckPath,
		&i.AutoDeploy,
		&i.BuildContext,
		&i.DockerfilePath,
		&i.BuildArgs,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DesiredState,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications WHERE id = $1
`

func (q *Queries) DeleteApplication(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApplication, id)
	return err
}

const getApplication = `-- name: GetApplication :one
SELECT id, org_id, name, slug, source_type, builder, git_repo_url, git_branch, image_ref, registry_creds_enc, exposed_port, healthcheck_path, auto_deploy, build_context, dockerfile_path, build_args, key_version, created_at, updated_at, desired_state FROM applications WHERE id = $1
`

func (q *Queries) GetApplication(ctx context.Context, id pgtype.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.SourceType,
		&i.Builder,
		&i.GitRepoUrl,
		&i.GitBranch,
		&i.ImageRef,
		&i.RegistryCredsEnc,
		&i.ExposedPort,
		&i.HealthcheckPath,
		&i.AutoDeploy,
		&i.BuildContext,
		&i.DockerfilePath,
		&i.BuildArgs,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DesiredState,
	)
	return i, err
}

const listApplicationsForOrg = `-- name: ListApplicationsForOrg :many
SELECT id, org_id, name, slug, source_type, builder, git_repo_url, git_branch, image_ref, registry_creds_enc, exposed_port, healthcheck_path, auto_deploy, build_context, dockerfile_path, build_args, key_version, created_at, updated_at, desired_state FROM applications WHERE org_id = $1 ORDER BY created_at
`

func (q *Queries) ListApplicationsForOrg(ctx context.Context, orgID pgtype.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.SourceType,
			&i.Builder,
			&i.GitRepoUrl,
			&i.GitBranch,
			&i.ImageRef,
			&i.RegistryCredsEnc,
			&i.ExposedPort,
			&i.HealthcheckPath,
			&i.AutoDeploy,
			&i.BuildContext,
			&i.DockerfilePath,
			&i.BuildArgs,
			&i.KeyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DesiredState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitAppsByBranch = `-- name: ListGitAppsByBranch :many
SELECT id, org_id, name, slug, source_type, builder, git_repo_url, git_branch, image_ref, registry_creds_enc, exposed_port, healthcheck_path, auto_deploy, build_context, dockerfile_path, build_args, key_version, created_at, updated_at, desired_state FROM applications WHERE source_type = 'git' AND git_branch = $1
`

func (q *Queries) ListGitAppsByBranch(ctx context.Context, gitBranch string) ([]Application, error) {
	rows, err := q.db.Query(ctx, listGitAppsByBranch, gitBranch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.SourceType,
			&i.Builder,
			&i.GitRepoUrl,
			&i.GitBranch,
			&i.ImageRef,
			&i.RegistryCredsEnc,
			&i.ExposedPort,
			&i.HealthcheckPath,
			&i.AutoDeploy,
			&i.BuildContext,
			&i.DockerfilePath,
			&i.BuildArgs,
			&i.KeyVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DesiredState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setApplicationDesiredState = `-- name: SetApplicationDesiredState :one
UPDATE applications SET desired_state = $2, updated_at = now()
WHERE id = $1
RETURNING id, org_id, name, slug, source_type, builder, git_repo_url, git_branch, image_ref, registry_creds_enc, exposed_port, healthcheck_path, auto_deploy, build_context, dockerfile_path, build_args, key_version, created_at, updated_at, desired_state
`

type SetApplicationDesiredStateParams struct {
	ID           pgtype.UUID
	DesiredState string
}

func (q *Queries) SetApplicationDesiredState(ctx context.Context, arg SetApplicationDesiredStateParams) (Application, error) {
	row := q.db.QueryRow(ctx, setApplicationDesiredState, arg.ID, arg.DesiredState)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.SourceType,
		&i.Builder,
		&i.GitRepoUrl,
		&i.GitBranch,
		&i.ImageRef,
		&i.RegistryCredsEnc,
		&i.ExposedPort,
		&i.HealthcheckPath,
		&i.AutoDeploy,
		&i.BuildContext,
		&i.DockerfilePath,
		&i.BuildArgs,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DesiredState,
	)
	return i, err
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications SET
    name = $2, builder = $3, git_branch = $4, image_ref = $5,
    exposed_port = $6, healthcheck_path = $7, auto_deploy = $8,
    build_context = $9, dockerfile_path = $10, build_args = $11,
    registry_creds_enc = $12, updated_at = now()
WHERE id = $1
RETURNING id, org_id, name, slug, source_type, builder, git_repo_url, git_branch, image_ref, registry_creds_enc, exposed_port, healthcheck_path, auto_deploy, build_context, dockerfile_path, build_args, key_version, created_at, updated_at, desired_state
`

type UpdateApplicationParams struct {
	ID               pgtype.UUID
	Name             string
	Builder          string
	GitBranch        string
	ImageRef         string
	ExposedPort      int32
	HealthcheckPath  string
	AutoDeploy       bool
	BuildContext     string
	DockerfilePath   string
	BuildArgs        []byte
	RegistryCredsEnc []byte
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication,
		arg.ID,
		arg.Name,
		arg.Builder,
		arg.GitBranch,
		arg.ImageRef,
		arg.ExposedPort,
		arg.HealthcheckPath,
		arg.AutoDeploy,
		arg.BuildContext,
		arg.DockerfilePath,
		arg.BuildArgs,
		arg.RegistryCredsEnc,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.SourceType,
		&i.Builder,
		&i.GitRepoUrl,
		&i.GitBranch,
		&i.ImageRef,
		&i.RegistryCredsEnc,
		&i.ExposedPort,
		&i.HealthcheckPath,
		&i.AutoDeploy,
		&i.BuildContext,
		&i.DockerfilePath,
		&i.BuildArgs,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DesiredState,
	)
	return i, err
}
