// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (actor_id, org_id, action, target_type, target_id, detail)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	ActorID    pgtype.UUID
	OrgID      pgtype.UUID
	Action     string
	TargetType string
	TargetID   string
	Detail     []byte
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorID,
		arg.OrgID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Detail,
	)
	return err
}

const listAuditAll = `-- name: ListAuditAll :many
SELECT a.id, a.actor_id, a.org_id, a.action, a.target_type, a.target_id,
       a.detail, a.created_at, u.email AS actor_email
FROM audit_log a LEFT JOIN users u ON u.id = a.actor_id
ORDER BY a.created_at DESC
LIMIT $1
`

type ListAuditAllRow struct {
	ID         pgtype.UUID
	ActorID    pgtype.UUID
	OrgID      pgtype.UUID
	Action     string
	TargetType string
	TargetID   string
	Detail     []byte
	CreatedAt  pgtype.Timestamptz
	ActorEmail pgtype.Text
}

func (q *Queries) ListAuditAll(ctx context.Context, limit int32) ([]ListAuditAllRow, error) {
	rows, err := q.db.Query(ctx, listAuditAll, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditAllRow
	for rows.Next() {
		var i ListAuditAllRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.OrgID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Detail,
			&i.CreatedAt,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditByOrg = `-- name: ListAuditByOrg :many
SELECT a.id, a.actor_id, a.org_id, a.action, a.target_type, a.target_id,
       a.detail, a.created_at, u.email AS actor_email
FROM audit_log a LEFT JOIN users u ON u.id = a.actor_id
WHERE a.org_id = $1
ORDER BY a.created_at DESC
LIMIT $2
`

type ListAuditByOrgParams struct {
	OrgID pgtype.UUID
	Limit int32
}

type ListAuditByOrgRow struct {
	ID         pgtype.UUID
	ActorID    pgtype.UUID
	OrgID      pgtype.UUID
	Action     string
	TargetType string
	TargetID   string
	Detail     []byte
	CreatedAt  pgtype.Timestamptz
	ActorEmail pgtype.Text
}

func (q *Queries) ListAuditByOrg(ctx context.Context, arg ListAuditByOrgParams) ([]ListAuditByOrgRow, error) {
	rows, err := q.db.Query(ctx, listAuditByOrg, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditByOrgRow
	for rows.Next() {
		var i ListAuditByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.OrgID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Detail,
			&i.CreatedAt,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAuditLog = `-- name: PurgeAuditLog :execrows
DELETE FROM audit_log WHERE created_at < $1
`

func (q *Queries) PurgeAuditLog(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeAuditLog, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
