// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: databases.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAttachmentsByInstance = `-- name: CountAttachmentsByInstance :one
SELECT COUNT(*) FROM database_attachments WHERE instance_id = $1
`

func (q *Queries) CountAttachmentsByInstance(ctx context.Context, instanceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAttachmentsByInstance, instanceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDatabaseAttachment = `-- name: CreateDatabaseAttachment :one
INSERT INTO database_attachments (
    instance_id, app_id, db_name, role_name, acl_user, db_index, secret
) VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING id, instance_id, app_id, db_name, role_name, acl_user, db_index, secret, created_at
`

type CreateDatabaseAttachmentParams struct {
	InstanceID pgtype.UUID
	AppID      pgtype.UUID
	DbName     pgtype.Text
	RoleName   pgtype.Text
	AclUser    pgtype.Text
	DbIndex    pgtype.Int4
	Secret     []byte
}

func (q *Queries) CreateDatabaseAttachment(ctx context.Context, arg CreateDatabaseAttachmentParams) (DatabaseAttachment, error) {
	row := q.db.QueryRow(ctx, createDatabaseAttachment,
		arg.InstanceID,
		arg.AppID,
		arg.DbName,
		arg.RoleName,
		arg.AclUser,
		arg.DbIndex,
		arg.Secret,
	)
	var i DatabaseAttachment
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.AppID,
		&i.DbName,
		&i.RoleName,
		&i.AclUser,
		&i.DbIndex,
		&i.Secret,
		&i.CreatedAt,
	)
	return i, err
}

const createDatabaseInstance = `-- name: CreateDatabaseInstance :one
INSERT INTO database_instances (
    org_id, name, engine, version, redis_mode, host_port, status, admin_secret
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
RETURNING id, org_id, name, engine, version, redis_mode, host_port, status, admin_secret, created_at
`

type CreateDatabaseInstanceParams struct {
	OrgID       pgtype.UUID
	Name        string
	Engine      string
	Version     string
	RedisMode   pgtype.Text
	HostPort    pgtype.Int4
	Status      string
	AdminSecret []byte
}

func (q *Queries) CreateDatabaseInstance(ctx context.Context, arg CreateDatabaseInstanceParams) (DatabaseInstance, error) {
	row := q.db.QueryRow(ctx, createDatabaseInstance,
		arg.OrgID,
		arg.Name,
		arg.Engine,
		arg.Version,
		arg.RedisMode,
		arg.HostPort,
		arg.Status,
		arg.AdminSecret,
	)
	var i DatabaseInstance
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.RedisMode,
		&i.HostPort,
		&i.Status,
		&i.AdminSecret,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDatabaseAttachment = `-- name: DeleteDatabaseAttachment :exec
DELETE FROM database_attachments WHERE id = $1
`

func (q *Queries) DeleteDatabaseAttachment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDatabaseAttachment, id)
	return err
}

const deleteDatabaseInstance = `-- name: DeleteDatabaseInstance :exec
DELETE FROM database_instances WHERE id = $1
`

func (q *Queries) DeleteDatabaseInstance(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDatabaseInstance, id)
	return err
}

const getDatabaseAttachment = `-- name: GetDatabaseAttachment :one
SELECT id, instance_id, app_id, db_name, role_name, acl_user, db_index, secret, created_at FROM database_attachments WHERE instance_id = $1 AND app_id = $2
`

type GetDatabaseAttachmentParams struct {
	InstanceID pgtype.UUID
	AppID      pgtype.UUID
}

func (q *Queries) GetDatabaseAttachment(ctx context.Context, arg GetDatabaseAttachmentParams) (DatabaseAttachment, error) {
	row := q.db.QueryRow(ctx, getDatabaseAttachment, arg.InstanceID, arg.AppID)
	var i DatabaseAttachment
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.AppID,
		&i.DbName,
		&i.RoleName,
		&i.AclUser,
		&i.DbIndex,
		&i.Secret,
		&i.CreatedAt,
	)
	return i, err
}

const getDatabaseInstance = `-- name: GetDatabaseInstance :one
SELECT id, org_id, name, engine, version, redis_mode, host_port, status, admin_secret, created_at FROM database_instances WHERE id = $1
`

func (q *Queries) GetDatabaseInstance(ctx context.Context, id pgtype.UUID) (DatabaseInstance, error) {
	row := q.db.QueryRow(ctx, getDatabaseInstance, id)
	var i DatabaseInstance
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Engine,
		&i.Version,
		&i.RedisMode,
		&i.HostPort,
		&i.Status,
		&i.AdminSecret,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByApp = `-- name: ListAttachmentsByApp :many
SELECT database_attachments.id, database_attachments.instance_id, database_attachments.app_id, database_attachments.db_name, database_attachments.role_name, database_attachments.acl_user, database_attachments.db_index, database_attachments.secret, database_attachments.created_at, di.engine, di.name AS instance_name, di.status
FROM database_attachments
JOIN database_instances di ON di.id = database_attachments.instance_id
WHERE database_attachments.app_id = $1
ORDER BY database_attachments.created_at
`

type ListAttachmentsByAppRow struct {
	DatabaseAttachment DatabaseAttachment
	Engine             string
	InstanceName       string
	Status             string
}

func (q *Queries) ListAttachmentsByApp(ctx context.Context, appID pgtype.UUID) ([]ListAttachmentsByAppRow, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttachmentsByAppRow
	for rows.Next() {
		var i ListAttachmentsByAppRow
		if err := rows.Scan(
			&i.DatabaseAttachment.ID,
			&i.DatabaseAttachment.InstanceID,
			&i.DatabaseAttachment.AppID,
			&i.DatabaseAttachment.DbName,
			&i.DatabaseAttachment.RoleName,
			&i.DatabaseAttachment.AclUser,
			&i.DatabaseAttachment.DbIndex,
			&i.DatabaseAttachment.Secret,
			&i.DatabaseAttachment.CreatedAt,
			&i.Engine,
			&i.InstanceName,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsByInstance = `-- name: ListAttachmentsByInstance :many
SELECT id, instance_id, app_id, db_name, role_name, acl_user, db_index, secret, created_at FROM database_attachments WHERE instance_id = $1 ORDER BY created_at
`

func (q *Queries) ListAttachmentsByInstance(ctx context.Context, instanceID pgtype.UUID) ([]DatabaseAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DatabaseAttachment
	for rows.Next() {
		var i DatabaseAttachment
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.AppID,
			&i.DbName,
			&i.RoleName,
			&i.AclUser,
			&i.DbIndex,
			&i.Secret,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDatabaseInstancesByOrg = `-- name: ListDatabaseInstancesByOrg :many
SELECT id, org_id, name, engine, version, redis_mode, host_port, status, admin_secret, created_at FROM database_instances WHERE org_id = $1 ORDER BY created_at
`

func (q *Queries) ListDatabaseInstancesByOrg(ctx context.Context, orgID pgtype.UUID) ([]DatabaseInstance, error) {
	rows, err := q.db.Query(ctx, listDatabaseInstancesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DatabaseInstance
	for rows.Next() {
		var i DatabaseInstance
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Engine,
			&i.Version,
			&i.RedisMode,
			&i.HostPort,
			&i.Status,
			&i.AdminSecret,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsedDbIndexes = `-- name: ListUsedDbIndexes :many
SELECT db_index FROM database_attachments WHERE instance_id = $1 AND db_index IS NOT NULL ORDER BY db_index
`

func (q *Queries) ListUsedDbIndexes(ctx context.Context, instanceID pgtype.UUID) ([]pgtype.Int4, error) {
	rows, err := q.db.Query(ctx, listUsedDbIndexes, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Int4
	for rows.Next() {
		var db_index pgtype.Int4
		if err := rows.Scan(&db_index); err != nil {
			return nil, err
		}
		items = append(items, db_index)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDatabaseInstanceStatus = `-- name: SetDatabaseInstanceStatus :exec
UPDATE database_instances SET status = $2 WHERE id = $1
`

type SetDatabaseInstanceStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) SetDatabaseInstanceStatus(ctx context.Context, arg SetDatabaseInstanceStatusParams) error {
	_, err := q.db.Exec(ctx, setDatabaseInstanceStatus, arg.ID, arg.Status)
	return err
}
