// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (app_id, trigger, actor, image_tag, commit_sha)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, app_id, trigger, status, commit_sha, image_tag, error, actor, created_at, started_at, finished_at
`

type CreateDeploymentParams struct {
	AppID     pgtype.UUID
	Trigger   string
	Actor     pgtype.UUID
	ImageTag  string
	CommitSha string
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.AppID,
		arg.Trigger,
		arg.Actor,
		arg.ImageTag,
		arg.CommitSha,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Trigger,
		&i.Status,
		&i.CommitSha,
		&i.ImageTag,
		&i.Error,
		&i.Actor,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteDeployment = `-- name: DeleteDeployment :exec
DELETE FROM deployments WHERE id = $1
`

func (q *Queries) DeleteDeployment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeployment, id)
	return err
}

const finishDeployment = `-- name: FinishDeployment :exec
UPDATE deployments SET status = $2, error = $3, finished_at = now() WHERE id = $1
`

type FinishDeploymentParams struct {
	ID     pgtype.UUID
	Status string
	Error  string
}

func (q *Queries) FinishDeployment(ctx context.Context, arg FinishDeploymentParams) error {
	_, err := q.db.Exec(ctx, finishDeployment, arg.ID, arg.Status, arg.Error)
	return err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, app_id, trigger, status, commit_sha, image_tag, error, actor, created_at, started_at, finished_at FROM deployments WHERE id = $1
`

func (q *Queries) GetDeployment(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Trigger,
		&i.Status,
		&i.CommitSha,
		&i.ImageTag,
		&i.Error,
		&i.Actor,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listDeploymentsForApp = `-- name: ListDeploymentsForApp :many
SELECT id, app_id, trigger, status, commit_sha, image_tag, error, actor, created_at, started_at, finished_at FROM deployments WHERE app_id = $1 ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListDeploymentsForApp(ctx context.Context, appID pgtype.UUID) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsForApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Trigger,
			&i.Status,
			&i.CommitSha,
			&i.ImageTag,
			&i.Error,
			&i.Actor,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrunableDeployments = `-- name: ListPrunableDeployments :many
SELECT id, app_id, trigger, status, commit_sha, image_tag, error, actor, created_at, started_at, finished_at FROM deployments WHERE app_id = $1 ORDER BY created_at DESC OFFSET $2
`

type ListPrunableDeploymentsParams struct {
	AppID  pgtype.UUID
	Offset int32
}

func (q *Queries) ListPrunableDeployments(ctx context.Context, arg ListPrunableDeploymentsParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listPrunableDeployments, arg.AppID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Trigger,
			&i.Status,
			&i.CommitSha,
			&i.ImageTag,
			&i.Error,
			&i.Actor,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeploymentStatus = `-- name: MarkDeploymentStatus :exec
UPDATE deployments SET status = $2,
    started_at = COALESCE(started_at, now())
WHERE id = $1
`

type MarkDeploymentStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) MarkDeploymentStatus(ctx context.Context, arg MarkDeploymentStatusParams) error {
	_, err := q.db.Exec(ctx, markDeploymentStatus, arg.ID, arg.Status)
	return err
}

const setDeploymentBuildInfo = `-- name: SetDeploymentBuildInfo :exec
UPDATE deployments SET commit_sha = $2, image_tag = $3 WHERE id = $1
`

type SetDeploymentBuildInfoParams struct {
	ID        pgtype.UUID
	CommitSha string
	ImageTag  string
}

func (q *Queries) SetDeploymentBuildInfo(ctx context.Context, arg SetDeploymentBuildInfoParams) error {
	_, err := q.db.Exec(ctx, setDeploymentBuildInfo, arg.ID, arg.CommitSha, arg.ImageTag)
	return err
}
