// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (app_id, hostname) VALUES ($1, $2) RETURNING id, app_id, hostname, status, last_checked_at, created_at
`

type CreateDomainParams struct {
	AppID    pgtype.UUID
	Hostname string
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain, arg.AppID, arg.Hostname)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Hostname,
		&i.Status,
		&i.LastCheckedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains WHERE id = $1 AND app_id = $2
`

type DeleteDomainParams struct {
	ID    pgtype.UUID
	AppID pgtype.UUID
}

func (q *Queries) DeleteDomain(ctx context.Context, arg DeleteDomainParams) error {
	_, err := q.db.Exec(ctx, deleteDomain, arg.ID, arg.AppID)
	return err
}

const listAllDomains = `-- name: ListAllDomains :many
SELECT id, app_id, hostname, status, last_checked_at, created_at FROM domains ORDER BY created_at
`

func (q *Queries) ListAllDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listAllDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Hostname,
			&i.Status,
			&i.LastCheckedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsForApp = `-- name: ListDomainsForApp :many
SELECT id, app_id, hostname, status, last_checked_at, created_at FROM domains WHERE app_id = $1 ORDER BY created_at
`

func (q *Queries) ListDomainsForApp(ctx context.Context, appID pgtype.UUID) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomainsForApp, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Hostname,
			&i.Status,
			&i.LastCheckedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDomainStatus = `-- name: UpdateDomainStatus :exec
UPDATE domains SET status = $2, last_checked_at = now() WHERE id = $1
`

type UpdateDomainStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateDomainStatus(ctx context.Context, arg UpdateDomainStatusParams) error {
	_, err := q.db.Exec(ctx, updateDomainStatus, arg.ID, arg.Status)
	return err
}
