// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: envvars.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEnvVar = `-- name: DeleteEnvVar :exec
DELETE FROM env_vars WHERE app_id = $1 AND key = $2
`

type DeleteEnvVarParams struct {
	AppID pgtype.UUID
	Key   string
}

func (q *Queries) DeleteEnvVar(ctx context.Context, arg DeleteEnvVarParams) error {
	_, err := q.db.Exec(ctx, deleteEnvVar, arg.AppID, arg.Key)
	return err
}

const listEnvVars = `-- name: ListEnvVars :many
SELECT app_id, key, value_enc, key_version, updated_at FROM env_vars WHERE app_id = $1 ORDER BY key
`

func (q *Queries) ListEnvVars(ctx context.Context, appID pgtype.UUID) ([]EnvVar, error) {
	rows, err := q.db.Query(ctx, listEnvVars, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvVar
	for rows.Next() {
		var i EnvVar
		if err := rows.Scan(
			&i.AppID,
			&i.Key,
			&i.ValueEnc,
			&i.KeyVersion,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnvVar = `-- name: UpsertEnvVar :exec
INSERT INTO env_vars (app_id, key, value_enc)
VALUES ($1, $2, $3)
ON CONFLICT (app_id, key) DO UPDATE SET value_enc = EXCLUDED.value_enc, updated_at = now()
`

type UpsertEnvVarParams struct {
	AppID    pgtype.UUID
	Key      string
	ValueEnc []byte
}

func (q *Queries) UpsertEnvVar(ctx context.Context, arg UpsertEnvVarParams) error {
	_, err := q.db.Exec(ctx, upsertEnvVar, arg.AppID, arg.Key, arg.ValueEnc)
	return err
}
