// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGithubInstallation = `-- name: DeleteGithubInstallation :exec
DELETE FROM github_installations WHERE org_id = $1
`

func (q *Queries) DeleteGithubInstallation(ctx context.Context, orgID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGithubInstallation, orgID)
	return err
}

const getGithubInstallation = `-- name: GetGithubInstallation :one
SELECT org_id, installation_id, account_login, created_at FROM github_installations WHERE org_id = $1
`

func (q *Queries) GetGithubInstallation(ctx context.Context, orgID pgtype.UUID) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getGithubInstallation, orgID)
	var i GithubInstallation
	err := row.Scan(
		&i.OrgID,
		&i.InstallationID,
		&i.AccountLogin,
		&i.CreatedAt,
	)
	return i, err
}

const upsertGithubInstallation = `-- name: UpsertGithubInstallation :one
INSERT INTO github_installations (org_id, installation_id, account_login)
VALUES ($1, $2, $3)
ON CONFLICT (org_id) DO UPDATE
    SET installation_id = EXCLUDED.installation_id, account_login = EXCLUDED.account_login
RETURNING org_id, installation_id, account_login, created_at
`

type UpsertGithubInstallationParams struct {
	OrgID          pgtype.UUID
	InstallationID int64
	AccountLogin   string
}

func (q *Queries) UpsertGithubInstallation(ctx context.Context, arg UpsertGithubInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, upsertGithubInstallation, arg.OrgID, arg.InstallationID, arg.AccountLogin)
	var i GithubInstallation
	err := row.Scan(
		&i.OrgID,
		&i.InstallationID,
		&i.AccountLogin,
		&i.CreatedAt,
	)
	return i, err
}
