// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hosts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHost = `-- name: CreateHost :one
INSERT INTO hosts (
    name, address, port, private_key_enc,
    apps_domain_suffix, letsencrypt_email
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, address, port, private_key_enc, key_version, host_key_fingerprint, status, engine_version, cpu_count, mem_total_mb, apps_domain_suffix, letsencrypt_email, created_at
`

type CreateHostParams struct {
	Name             string
	Address          string
	Port             int32
	PrivateKeyEnc    []byte
	AppsDomainSuffix string
	LetsencryptEmail string
}

func (q *Queries) CreateHost(ctx context.Context, arg CreateHostParams) (Host, error) {
	row := q.db.QueryRow(ctx, createHost,
		arg.Name,
		arg.Address,
		arg.Port,
		arg.PrivateKeyEnc,
		arg.AppsDomainSuffix,
		arg.LetsencryptEmail,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Port,
		&i.PrivateKeyEnc,
		&i.KeyVersion,
		&i.HostKeyFingerprint,
		&i.Status,
		&i.EngineVersion,
		&i.CpuCount,
		&i.MemTotalMb,
		&i.AppsDomainSuffix,
		&i.LetsencryptEmail,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHost = `-- name: DeleteHost :exec
DELETE FROM hosts WHERE id = $1
`

func (q *Queries) DeleteHost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteHost, id)
	return err
}

const getHost = `-- name: GetHost :one
SELECT id, name, address, port, private_key_enc, key_version, host_key_fingerprint, status, engine_version, cpu_count, mem_total_mb, apps_domain_suffix, letsencrypt_email, created_at FROM hosts WHERE id = $1
`

func (q *Queries) GetHost(ctx context.Context, id pgtype.UUID) (Host, error) {
	row := q.db.QueryRow(ctx, getHost, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Port,
		&i.PrivateKeyEnc,
		&i.KeyVersion,
		&i.HostKeyFingerprint,
		&i.Status,
		&i.EngineVersion,
		&i.CpuCount,
		&i.MemTotalMb,
		&i.AppsDomainSuffix,
		&i.LetsencryptEmail,
		&i.CreatedAt,
	)
	return i, err
}

const listHosts = `-- name: ListHosts :many
SELECT id, name, address, port, private_key_enc, key_version, host_key_fingerprint, status, engine_version, cpu_count, mem_total_mb, apps_domain_suffix, letsencrypt_email, created_at FROM hosts ORDER BY created_at
`

func (q *Queries) ListHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.Query(ctx, listHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Port,
			&i.PrivateKeyEnc,
			&i.KeyVersion,
			&i.HostKeyFingerprint,
			&i.Status,
			&i.EngineVersion,
			&i.CpuCount,
			&i.MemTotalMb,
			&i.AppsDomainSuffix,
			&i.LetsencryptEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinHostFingerprint = `-- name: PinHostFingerprint :exec
UPDATE hosts SET host_key_fingerprint = $2 WHERE id = $1
`

type PinHostFingerprintParams struct {
	ID                 pgtype.UUID
	HostKeyFingerprint pgtype.Text
}

func (q *Queries) PinHostFingerprint(ctx context.Context, arg PinHostFingerprintParams) error {
	_, err := q.db.Exec(ctx, pinHostFingerprint, arg.ID, arg.HostKeyFingerprint)
	return err
}

const setHostKey = `-- name: SetHostKey :exec
UPDATE hosts SET private_key_enc = $2, key_version = $3 WHERE id = $1
`

type SetHostKeyParams struct {
	ID            pgtype.UUID
	PrivateKeyEnc []byte
	KeyVersion    int32
}

func (q *Queries) SetHostKey(ctx context.Context, arg SetHostKeyParams) error {
	_, err := q.db.Exec(ctx, setHostKey, arg.ID, arg.PrivateKeyEnc, arg.KeyVersion)
	return err
}

const updateHostStatus = `-- name: UpdateHostStatus :exec
UPDATE hosts SET status = $2, engine_version = $3,
                 cpu_count = $4, mem_total_mb = $5
WHERE id = $1
`

type UpdateHostStatusParams struct {
	ID            pgtype.UUID
	Status        string
	EngineVersion pgtype.Text
	CpuCount      pgtype.Int4
	MemTotalMb    pgtype.Int8
}

func (q *Queries) UpdateHostStatus(ctx context.Context, arg UpdateHostStatusParams) error {
	_, err := q.db.Exec(ctx, updateHostStatus,
		arg.ID,
		arg.Status,
		arg.EngineVersion,
		arg.CpuCount,
		arg.MemTotalMb,
	)
	return err
}
