// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hostmetrics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHostMetric = `-- name: CreateHostMetric :exec
INSERT INTO host_metrics (
    cpu_pct, mem_used_bytes, mem_total_bytes,
    disk_free_bytes, disk_total_bytes, containers, running_apps
) VALUES ($1,$2,$3,$4,$5,$6,$7)
`

type CreateHostMetricParams struct {
	CpuPct         float64
	MemUsedBytes   int64
	MemTotalBytes  int64
	DiskFreeBytes  int64
	DiskTotalBytes int64
	Containers     int32
	RunningApps    int32
}

func (q *Queries) CreateHostMetric(ctx context.Context, arg CreateHostMetricParams) error {
	_, err := q.db.Exec(ctx, createHostMetric,
		arg.CpuPct,
		arg.MemUsedBytes,
		arg.MemTotalBytes,
		arg.DiskFreeBytes,
		arg.DiskTotalBytes,
		arg.Containers,
		arg.RunningApps,
	)
	return err
}

const latestHostMetric = `-- name: LatestHostMetric :one
SELECT created_at, cpu_pct, mem_used_bytes, mem_total_bytes, disk_free_bytes, disk_total_bytes, containers, running_apps FROM host_metrics
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) LatestHostMetric(ctx context.Context) (HostMetric, error) {
	row := q.db.QueryRow(ctx, latestHostMetric)
	var i HostMetric
	err := row.Scan(
		&i.CreatedAt,
		&i.CpuPct,
		&i.MemUsedBytes,
		&i.MemTotalBytes,
		&i.DiskFreeBytes,
		&i.DiskTotalBytes,
		&i.Containers,
		&i.RunningApps,
	)
	return i, err
}

const listHostMetricsSince = `-- name: ListHostMetricsSince :many
SELECT created_at, cpu_pct, mem_used_bytes, mem_total_bytes, disk_free_bytes, disk_total_bytes, containers, running_apps FROM host_metrics
WHERE created_at >= $1
ORDER BY created_at
`

func (q *Queries) ListHostMetricsSince(ctx context.Context, createdAt pgtype.Timestamptz) ([]HostMetric, error) {
	rows, err := q.db.Query(ctx, listHostMetricsSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HostMetric
	for rows.Next() {
		var i HostMetric
		if err := rows.Scan(
			&i.CreatedAt,
			&i.CpuPct,
			&i.MemUsedBytes,
			&i.MemTotalBytes,
			&i.DiskFreeBytes,
			&i.DiskTotalBytes,
			&i.Containers,
			&i.RunningApps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestAppMetrics = `-- name: ListLatestAppMetrics :many
SELECT DISTINCT ON (m.app_id)
    m.app_id, a.org_id, a.name, a.slug, a.desired_state,
    m.created_at, m.cpu_pct, m.mem_bytes, m.mem_limit_bytes,
    m.req_rate, m.err_rate, m.p95_ms
FROM app_metrics m
JOIN applications a ON a.id = m.app_id
ORDER BY m.app_id, m.created_at DESC
`

type ListLatestAppMetricsRow struct {
	AppID         pgtype.UUID
	OrgID         pgtype.UUID
	Name          string
	Slug          string
	DesiredState  string
	CreatedAt     pgtype.Timestamptz
	CpuPct        float64
	MemBytes      int64
	MemLimitBytes int64
	ReqRate       float64
	ErrRate       float64
	P95Ms         float64
}

// The newest sample for every app that has one, with the app's identity, for
// the all-apps overview. DISTINCT ON keeps this a single index scan rather
// than one LatestAppMetric query per app.
func (q *Queries) ListLatestAppMetrics(ctx context.Context) ([]ListLatestAppMetricsRow, error) {
	rows, err := q.db.Query(ctx, listLatestAppMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestAppMetricsRow
	for rows.Next() {
		var i ListLatestAppMetricsRow
		if err := rows.Scan(
			&i.AppID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.DesiredState,
			&i.CreatedAt,
			&i.CpuPct,
			&i.MemBytes,
			&i.MemLimitBytes,
			&i.ReqRate,
			&i.ErrRate,
			&i.P95Ms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeHostMetrics = `-- name: PurgeHostMetrics :execrows
DELETE FROM host_metrics WHERE created_at < now() - interval '48 hours'
`

func (q *Queries) PurgeHostMetrics(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeHostMetrics)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
