// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (org_id, token_hash, role, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, token_hash, role, expires_at, created_by, revoked_at, created_at
`

type CreateInviteParams struct {
	OrgID     pgtype.UUID
	TokenHash []byte
	Role      string
	ExpiresAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.OrgID,
		arg.TokenHash,
		arg.Role,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TokenHash,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT id, org_id, token_hash, role, expires_at, created_by, revoked_at, created_at FROM invites WHERE token_hash = $1
`

func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash []byte) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TokenHash,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitesForOrg = `-- name: ListInvitesForOrg :many
SELECT id, org_id, token_hash, role, expires_at, created_by, revoked_at, created_at FROM invites WHERE org_id = $1 AND revoked_at IS NULL ORDER BY created_at
`

func (q *Queries) ListInvitesForOrg(ctx context.Context, orgID pgtype.UUID) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvitesForOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TokenHash,
			&i.Role,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeInvites = `-- name: PurgeInvites :execrows
DELETE FROM invites
WHERE expires_at < now() - interval '7 days'
   OR (revoked_at IS NOT NULL AND revoked_at < now() - interval '7 days')
`

func (q *Queries) PurgeInvites(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeInvites)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeInvite = `-- name: RevokeInvite :exec
UPDATE invites SET revoked_at = now() WHERE id = $1 AND org_id = $2
`

type RevokeInviteParams struct {
	ID    pgtype.UUID
	OrgID pgtype.UUID
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) error {
	_, err := q.db.Exec(ctx, revokeInvite, arg.ID, arg.OrgID)
	return err
}
