// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID               pgtype.UUID
	OrgID            pgtype.UUID
	Name             string
	Slug             string
	SourceType       string
	Builder          string
	GitRepoUrl       string
	GitBranch        string
	ImageRef         string
	RegistryCredsEnc []byte
	ExposedPort      int32
	HealthcheckPath  string
	AutoDeploy       bool
	BuildContext     string
	DockerfilePath   string
	BuildArgs        []byte
	KeyVersion       int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Deployment struct {
	ID         pgtype.UUID
	AppID      pgtype.UUID
	Trigger    string
	Status     string
	CommitSha  string
	ImageTag   string
	Error      string
	Actor      pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

type Domain struct {
	ID            pgtype.UUID
	AppID         pgtype.UUID
	Hostname      string
	Status        string
	LastCheckedAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type EnvVar struct {
	AppID      pgtype.UUID
	Key        string
	ValueEnc   []byte
	KeyVersion int32
	UpdatedAt  pgtype.Timestamptz
}

type GithubInstallation struct {
	OrgID          pgtype.UUID
	InstallationID int64
	AccountLogin   string
	CreatedAt      pgtype.Timestamptz
}

type InstanceSetting struct {
	Key       string
	Value     []byte
	UpdatedAt pgtype.Timestamptz
}

type Invite struct {
	ID        pgtype.UUID
	OrgID     pgtype.UUID
	TokenHash []byte
	Role      string
	ExpiresAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Membership struct {
	OrgID     pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

type Organization struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	FamilyID         pgtype.UUID
	AccessHash       []byte
	RefreshHash      []byte
	AccessExpiresAt  pgtype.Timestamptz
	RefreshExpiresAt pgtype.Timestamptz
	RotatedAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	Email           string
	PasswordHash    string
	IsInstanceAdmin bool
	CreatedAt       pgtype.Timestamptz
}
