// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InstanceSetting struct {
	Key       string
	Value     []byte
	UpdatedAt pgtype.Timestamptz
}
