// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppMetric struct {
	AppID         pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	CpuPct        float64
	MemBytes      int64
	MemLimitBytes int64
	NetRxBytes    int64
	NetTxBytes    int64
	ReqRate       float64
	ErrRate       float64
	P50Ms         float64
	P95Ms         float64
}

type Application struct {
	ID               pgtype.UUID
	OrgID            pgtype.UUID
	Name             string
	Slug             string
	SourceType       string
	Builder          string
	GitRepoUrl       string
	GitBranch        string
	ImageRef         string
	RegistryCredsEnc []byte
	ExposedPort      int32
	HealthcheckPath  string
	AutoDeploy       bool
	BuildContext     string
	DockerfilePath   string
	BuildArgs        []byte
	KeyVersion       int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DesiredState     string
	MemLimit         pgtype.Text
	CpuLimit         pgtype.Text
	PidsLimit        pgtype.Int4
	NotifyOnSuccess  bool
}

type AuthIdentity struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Issuer    string
	Subject   string
	Email     string
	CreatedAt pgtype.Timestamptz
}

type DatabaseAttachment struct {
	ID         pgtype.UUID
	InstanceID pgtype.UUID
	AppID      pgtype.UUID
	DbName     pgtype.Text
	RoleName   pgtype.Text
	AclUser    pgtype.Text
	DbIndex    pgtype.Int4
	Secret     []byte
	CreatedAt  pgtype.Timestamptz
}

type DatabaseInstance struct {
	ID          pgtype.UUID
	OrgID       pgtype.UUID
	Name        string
	Engine      string
	Version     string
	RedisMode   pgtype.Text
	HostPort    pgtype.Int4
	Status      string
	AdminSecret []byte
	CreatedAt   pgtype.Timestamptz
}

type Deployment struct {
	ID         pgtype.UUID
	AppID      pgtype.UUID
	Trigger    string
	Status     string
	CommitSha  string
	ImageTag   string
	Error      string
	Actor      pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

type Domain struct {
	ID            pgtype.UUID
	AppID         pgtype.UUID
	Hostname      string
	Status        string
	LastCheckedAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type EnvVar struct {
	AppID      pgtype.UUID
	Key        string
	ValueEnc   []byte
	KeyVersion int32
	UpdatedAt  pgtype.Timestamptz
}

type GithubInstallation struct {
	OrgID          pgtype.UUID
	InstallationID int64
	AccountLogin   string
	CreatedAt      pgtype.Timestamptz
}

type InstanceSetting struct {
	Key       string
	Value     []byte
	UpdatedAt pgtype.Timestamptz
}

type Invite struct {
	ID        pgtype.UUID
	OrgID     pgtype.UUID
	TokenHash []byte
	Role      string
	ExpiresAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Email     pgtype.Text
}

type Membership struct {
	OrgID     pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

type Organization struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	FamilyID         pgtype.UUID
	AccessHash       []byte
	RefreshHash      []byte
	AccessExpiresAt  pgtype.Timestamptz
	RefreshExpiresAt pgtype.Timestamptz
	RotatedAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	Email           string
	PasswordHash    pgtype.Text
	IsInstanceAdmin bool
	CreatedAt       pgtype.Timestamptz
}
