// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oidc.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO auth_identities (user_id, issuer, subject, email)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, issuer, subject, email, created_at
`

type CreateIdentityParams struct {
	UserID  pgtype.UUID
	Issuer  string
	Subject string
	Email   string
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.UserID,
		arg.Issuer,
		arg.Subject,
		arg.Email,
	)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentityByIssuerSubject = `-- name: GetIdentityByIssuerSubject :one
SELECT id, user_id, issuer, subject, email, created_at FROM auth_identities WHERE issuer = $1 AND subject = $2
`

type GetIdentityByIssuerSubjectParams struct {
	Issuer  string
	Subject string
}

func (q *Queries) GetIdentityByIssuerSubject(ctx context.Context, arg GetIdentityByIssuerSubjectParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentityByIssuerSubject, arg.Issuer, arg.Subject)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
