// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, family_id, access_hash, refresh_hash, access_expires_at, refresh_expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, family_id, access_hash, refresh_hash, access_expires_at, refresh_expires_at, rotated_at, revoked_at, created_at
`

type CreateSessionParams struct {
	UserID           pgtype.UUID
	FamilyID         pgtype.UUID
	AccessHash       []byte
	RefreshHash      []byte
	AccessExpiresAt  pgtype.Timestamptz
	RefreshExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.FamilyID,
		arg.AccessHash,
		arg.RefreshHash,
		arg.AccessExpiresAt,
		arg.RefreshExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.AccessHash,
		&i.RefreshHash,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByAccessHash = `-- name: GetSessionByAccessHash :one
SELECT id, user_id, family_id, access_hash, refresh_hash, access_expires_at, refresh_expires_at, rotated_at, revoked_at, created_at FROM sessions WHERE access_hash = $1
`

func (q *Queries) GetSessionByAccessHash(ctx context.Context, accessHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByAccessHash, accessHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.AccessHash,
		&i.RefreshHash,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, user_id, family_id, access_hash, refresh_hash, access_expires_at, refresh_expires_at, rotated_at, revoked_at, created_at FROM sessions WHERE refresh_hash = $1
`

func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.AccessHash,
		&i.RefreshHash,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markSessionRotated = `-- name: MarkSessionRotated :exec
UPDATE sessions SET rotated_at = now() WHERE id = $1
`

func (q *Queries) MarkSessionRotated(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markSessionRotated, id)
	return err
}

const purgeSessions = `-- name: PurgeSessions :execrows
DELETE FROM sessions
WHERE refresh_expires_at < now()
   OR (revoked_at IS NOT NULL AND revoked_at < now() - interval '24 hours')
`

func (q *Queries) PurgeSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionFamily = `-- name: RevokeSessionFamily :exec
UPDATE sessions SET revoked_at = now() WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionFamily(ctx context.Context, familyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSessionFamily, familyID)
	return err
}
