// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"
)

const deleteInstanceSetting = `-- name: DeleteInstanceSetting :exec
DELETE FROM instance_settings WHERE key = $1
`

func (q *Queries) DeleteInstanceSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteInstanceSetting, key)
	return err
}

const getInstanceSetting = `-- name: GetInstanceSetting :one
SELECT key, value, updated_at FROM instance_settings WHERE key = $1
`

func (q *Queries) GetInstanceSetting(ctx context.Context, key string) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, getInstanceSetting, key)
	var i InstanceSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const upsertInstanceSetting = `-- name: UpsertInstanceSetting :one
INSERT INTO instance_settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
RETURNING key, value, updated_at
`

type UpsertInstanceSettingParams struct {
	Key   string
	Value []byte
}

func (q *Queries) UpsertInstanceSetting(ctx context.Context, arg UpsertInstanceSettingParams) (InstanceSetting, error) {
	row := q.db.QueryRow(ctx, upsertInstanceSetting, arg.Key, arg.Value)
	var i InstanceSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
