package builder

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// Go generates a lean multi-stage Dockerfile for Go modules: a static binary
// built with the module and build caches, copied into a minimal alpine
// runtime. It only matches when it can confidently resolve a single main
// package, so ambiguous layouts fall through to Nixpacks.
type Go struct{}

func (Go) Name() string { return "go" }

func (Go) Match(dir string) bool {
	if !exists(filepath.Join(dir, "go.mod")) {
		return false
	}
	_, ok := goMainPkg(dir)
	return ok
}

var (
	goVersionRe   = regexp.MustCompile(`(?m)^go\s+(\d+\.\d+)`)
	packageMainRe = regexp.MustCompile(`(?m)^package\s+main\b`)
)

func (Go) Dockerfile(dir string) (string, error) {
	pkg, ok := goMainPkg(dir)
	if !ok {
		return "", fmt.Errorf("could not resolve a single main package")
	}
	goVer := "1.23"
	if raw, err := os.ReadFile(filepath.Join(dir, "go.mod")); err == nil {
		if m := goVersionRe.FindSubmatch(raw); m != nil {
			goVer = string(m[1])
		}
	}

	var b strings.Builder
	b.WriteString("# syntax=docker/dockerfile:1\n")
	b.WriteString("# generated by Cargo — static Go build\n")
	fmt.Fprintf(&b, "FROM golang:%s-alpine AS build\n", goVer)
	b.WriteString("WORKDIR /src\n")
	// go.* copies go.mod (guaranteed) and go.sum/go.work when present.
	b.WriteString("COPY go.* ./\n")
	b.WriteString("RUN --mount=type=cache,target=/go/pkg/mod go mod download\n")
	b.WriteString("COPY . .\n")
	fmt.Fprintf(&b, "RUN --mount=type=cache,target=/go/pkg/mod --mount=type=cache,target=/root/.cache/go-build CGO_ENABLED=0 go build -ldflags=\"-s -w\" -o /out/app %s\n", pkg)

	b.WriteString("\nFROM alpine:3.21 AS run\n")
	b.WriteString("RUN apk add --no-cache ca-certificates && addgroup -S app && adduser -S app -G app\n")
	b.WriteString("WORKDIR /app\n")
	b.WriteString("COPY --from=build /out/app /app/app\n")
	b.WriteString("USER app\n")
	b.WriteString("CMD [\"./app\"]\n")
	return b.String(), nil
}

// goMainPkg resolves the package to build: the module root if it has a
// `package main` file, else a single cmd/<name> that does. Returns false when
// it can't confidently pick one (→ Nixpacks fallback).
func goMainPkg(dir string) (string, bool) {
	if hasGoMain(dir) {
		return ".", true
	}
	entries, err := os.ReadDir(filepath.Join(dir, "cmd"))
	if err != nil {
		return "", false
	}
	found := ""
	for _, e := range entries {
		if e.IsDir() && hasGoMain(filepath.Join(dir, "cmd", e.Name())) {
			if found != "" {
				return "", false // ambiguous: more than one cmd main
			}
			found = "./cmd/" + e.Name()
		}
	}
	return found, found != ""
}

// hasGoMain reports whether dir has a non-test .go file declaring package main.
func hasGoMain(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		if raw, err := os.ReadFile(filepath.Join(dir, name)); err == nil && packageMainRe.Match(raw) {
			return true
		}
	}
	return false
}
