package builder

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// Java generates a multi-stage Dockerfile for Maven or Gradle projects: build
// an executable jar (e.g. a Spring Boot fat jar), then run it on a slim JRE.
// Assumes the build produces a runnable jar; non-executable-jar projects can
// supply their own Dockerfile.
type Java struct{}

func (Java) Name() string { return "java" }

func (Java) Match(dir string) bool {
	return exists(filepath.Join(dir, "pom.xml")) ||
		exists(filepath.Join(dir, "build.gradle")) ||
		exists(filepath.Join(dir, "build.gradle.kts"))
}

var (
	mavenJavaRe  = regexp.MustCompile(`<(?:java\.version|maven\.compiler\.release|maven\.compiler\.target)>\s*(\d+)`)
	gradleJavaRe = regexp.MustCompile(`(?:sourceCompatibility|targetCompatibility|languageVersion|JavaLanguageVersion\.of\()\D*?(\d+)`)
	// jar selection: the executable jar, excluding Gradle's -plain and
	// Maven's -sources/-javadoc classifier jars.
	jarPick = "! -name '*-plain.jar' ! -name '*-sources.jar' ! -name '*-javadoc.jar'"
)

func (Java) Dockerfile(dir string) (string, error) {
	jdk := detectJDK(dir)
	var b strings.Builder
	b.WriteString("# syntax=docker/dockerfile:1\n")
	b.WriteString("# generated by Cargo — Java build → slim JRE runtime\n")

	if exists(filepath.Join(dir, "pom.xml")) {
		mavenBuild(&b, jdk)
	} else {
		gradleBuild(&b, jdk, exists(filepath.Join(dir, "gradlew")))
	}

	fmt.Fprintf(&b, "\nFROM eclipse-temurin:%s-jre-alpine AS run\n", jdk)
	b.WriteString("RUN addgroup -S app && adduser -S app -G app\n")
	b.WriteString("WORKDIR /app\n")
	b.WriteString("COPY --from=build --chown=app:app /out/app.jar ./app.jar\n")
	b.WriteString("USER app\n")
	b.WriteString("CMD [\"java\",\"-jar\",\"app.jar\"]\n")
	return b.String(), nil
}

func mavenBuild(b *strings.Builder, jdk string) {
	fmt.Fprintf(b, "FROM maven:3.9-eclipse-temurin-%s AS build\n", jdk)
	b.WriteString("WORKDIR /app\n")
	b.WriteString("COPY . .\n")
	b.WriteString("RUN --mount=type=cache,target=/root/.m2 mvn -B -q -DskipTests package\n")
	fmt.Fprintf(b, "RUN mkdir -p /out && cp \"$(find target -maxdepth 1 -name '*.jar' %s | head -n1)\" /out/app.jar\n", jarPick)
}

func gradleBuild(b *strings.Builder, jdk string, wrapper bool) {
	if wrapper {
		// Respect the project's Gradle version via the wrapper; run as root
		// on a plain JDK image to avoid the gradle image's non-root writes.
		fmt.Fprintf(b, "FROM eclipse-temurin:%s-jdk AS build\n", jdk)
		b.WriteString("WORKDIR /app\n")
		b.WriteString("COPY . .\n")
		b.WriteString("RUN --mount=type=cache,target=/root/.gradle chmod +x gradlew && (./gradlew --no-daemon -x test bootJar 2>/dev/null || ./gradlew --no-daemon -x test build)\n")
	} else {
		fmt.Fprintf(b, "FROM gradle:8-jdk%s AS build\n", jdk)
		b.WriteString("WORKDIR /home/gradle/src\n")
		b.WriteString("COPY --chown=gradle:gradle . .\n")
		b.WriteString("RUN --mount=type=cache,target=/home/gradle/.gradle,uid=1000,gid=1000 gradle --no-daemon -x test bootJar 2>/dev/null || gradle --no-daemon -x test build\n")
	}
	dir := "build/libs"
	fmt.Fprintf(b, "RUN mkdir -p /out && cp \"$(find %s -maxdepth 1 -name '*.jar' %s | head -n1)\" /out/app.jar\n", dir, jarPick)
}

func detectJDK(dir string) string {
	if raw, err := os.ReadFile(filepath.Join(dir, "pom.xml")); err == nil {
		if m := mavenJavaRe.FindSubmatch(raw); m != nil {
			return string(m[1])
		}
	}
	for _, f := range []string{"build.gradle", "build.gradle.kts"} {
		if raw, err := os.ReadFile(filepath.Join(dir, f)); err == nil {
			if m := gradleJavaRe.FindSubmatch(raw); m != nil {
				return string(m[1])
			}
		}
	}
	return "21" // current LTS
}
