package builder

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

// Node generates a lean multi-stage Dockerfile for npm/pnpm/yarn projects.
// Bun projects (bun.lockb) are left to Nixpacks since they need the bun runtime.
type Node struct{}

func (Node) Name() string { return "node" }

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func (Node) Match(dir string) bool {
	return exists(filepath.Join(dir, "package.json")) && !exists(filepath.Join(dir, "bun.lockb"))
}

type nodePkg struct {
	Scripts        map[string]string `json:"scripts"`
	Main           string            `json:"main"`
	PackageManager string            `json:"packageManager"`
	Engines        struct {
		Node string `json:"node"`
	} `json:"engines"`
}

// pmSpec describes how to drive one package manager inside the Dockerfile.
type pmSpec struct {
	setup      string   // command to provision the PM (or ""); e.g. "npm install -g pnpm@9"
	lockFile   string   // "" if none present
	install    string   // full install command
	runv       []string // script runner prefix, e.g. ["pnpm","run"]
	prune      string   // "" to skip (keep all deps)
	cacheMount string   // BuildKit cache mount for the package store, or ""
}

var nodeMajorRe = regexp.MustCompile(`\d+`)

func (Node) Dockerfile(dir string) (string, error) {
	raw, err := os.ReadFile(filepath.Join(dir, "package.json"))
	if err != nil {
		return "", err
	}
	var pkg nodePkg
	if err := json.Unmarshal(raw, &pkg); err != nil {
		return "", fmt.Errorf("parse package.json: %w", err)
	}

	nodeVer := "22"
	if m := nodeMajorRe.FindString(pkg.Engines.Node); m != "" {
		nodeVer = m
	}
	pm := detectPM(dir, pkg)
	hasBuild := pkg.Scripts["build"] != ""

	var b strings.Builder
	b.WriteString("# syntax=docker/dockerfile:1\n")
	b.WriteString("# generated by Cargo — lean multi-stage Node build\n")

	// ---- build stage ----
	fmt.Fprintf(&b, "FROM node:%s-alpine AS build\n", nodeVer)
	b.WriteString("WORKDIR /app\n")
	if pm.setup != "" {
		fmt.Fprintf(&b, "RUN %s\n", pm.setup)
	}
	if pm.lockFile != "" {
		fmt.Fprintf(&b, "COPY package.json %s ./\n", pm.lockFile)
	} else {
		b.WriteString("COPY package.json ./\n")
	}
	if pm.cacheMount != "" {
		fmt.Fprintf(&b, "RUN %s %s\n", pm.cacheMount, pm.install)
	} else {
		fmt.Fprintf(&b, "RUN %s\n", pm.install)
	}
	b.WriteString("COPY . .\n")
	if hasBuild {
		fmt.Fprintf(&b, "RUN %s build\n", strings.Join(pm.runv, " "))
	}
	if pm.prune != "" {
		fmt.Fprintf(&b, "RUN %s\n", pm.prune)
	}
	// Drop regenerable caches and the repo before copying into the runtime:
	// Next's build cache and .git can be hundreds of MB and only bloat the
	// image / slow the export.
	b.WriteString("RUN rm -rf .git .next/cache node_modules/.cache 2>/dev/null || true\n")

	// ---- runtime stage (only prod deps + built output) ----
	fmt.Fprintf(&b, "\nFROM node:%s-alpine AS run\n", nodeVer)
	b.WriteString("WORKDIR /app\n")
	b.WriteString("ENV NODE_ENV=production\n")
	b.WriteString("RUN addgroup -S app && adduser -S app -G app\n")
	b.WriteString("COPY --from=build --chown=app:app /app ./\n")
	b.WriteString("USER app\n")
	fmt.Fprintf(&b, "CMD %s\n", nodeStart(pkg))
	return b.String(), nil
}

// detectPM picks the package manager from the lockfiles present and how to
// provision it. Corepack is used only when package.json pins a version via
// "packageManager" (so it installs that exact version); otherwise the PM is
// installed at a lockfile-appropriate version via npm. This avoids corepack's
// default behavior of fetching the *latest* PM, which can be incompatible with
// the project's Node (e.g. latest pnpm needs Node 20+, breaking a Node 18 app).
func detectPM(dir string, pkg nodePkg) pmSpec {
	switch {
	case exists(filepath.Join(dir, "pnpm-lock.yaml")):
		spec := pmSpec{
			lockFile:   "pnpm-lock.yaml",
			install:    "pnpm install --frozen-lockfile",
			runv:       []string{"pnpm", "run"},
			prune:      "pnpm prune --prod",
			cacheMount: "--mount=type=cache,target=/root/.local/share/pnpm/store",
		}
		if strings.HasPrefix(pkg.PackageManager, "pnpm@") {
			spec.setup = "corepack enable"
		} else {
			spec.setup = "npm install -g pnpm@" + pnpmMajor(dir)
		}
		return spec
	case exists(filepath.Join(dir, "yarn.lock")):
		spec := pmSpec{
			lockFile:   "yarn.lock",
			runv:       []string{"yarn", "run"},
			cacheMount: "--mount=type=cache,target=/usr/local/share/.cache/yarn",
		}
		if yarnIsBerry(dir) || (strings.HasPrefix(pkg.PackageManager, "yarn@") && !strings.HasPrefix(pkg.PackageManager, "yarn@1")) {
			// Berry manages itself via corepack; keep all deps (its prune model differs).
			spec.setup = "corepack enable"
			spec.install = "yarn install --immutable"
		} else {
			spec.setup = "npm install -g yarn@1"
			spec.install = "yarn install --frozen-lockfile --production=false"
		}
		return spec
	case exists(filepath.Join(dir, "package-lock.json")):
		return pmSpec{
			lockFile:   "package-lock.json",
			install:    "npm ci",
			runv:       []string{"npm", "run"},
			prune:      "npm prune --omit=dev",
			cacheMount: "--mount=type=cache,target=/root/.npm",
		}
	default: // no lockfile
		return pmSpec{
			install:    "npm install",
			runv:       []string{"npm", "run"},
			prune:      "npm prune --omit=dev",
			cacheMount: "--mount=type=cache,target=/root/.npm",
		}
	}
}

var pnpmLockVersionRe = regexp.MustCompile(`lockfileVersion:\s*['"]?(\d+)(?:\.(\d+))?`)

// pnpmMajor maps pnpm-lock.yaml's lockfileVersion to a compatible pnpm major:
// lockfile 9.x→pnpm 9, 6.x→pnpm 8, 5.x→pnpm 7. Defaults to 9.
func pnpmMajor(dir string) string {
	raw, err := os.ReadFile(filepath.Join(dir, "pnpm-lock.yaml"))
	if err != nil {
		return "9"
	}
	m := pnpmLockVersionRe.FindSubmatch(raw)
	if m == nil {
		return "9"
	}
	major, _ := strconv.Atoi(string(m[1]))
	switch {
	case major >= 9:
		return "9"
	case major == 6:
		return "8"
	case major == 5:
		return "7"
	default:
		return "9"
	}
}

// yarnIsBerry reports whether yarn.lock is a Yarn Berry (v2+) lockfile.
func yarnIsBerry(dir string) bool {
	raw, err := os.ReadFile(filepath.Join(dir, "yarn.lock"))
	if err != nil {
		return false
	}
	return strings.Contains(string(raw), "__metadata:")
}

// nodeStart returns the CMD (JSON exec form). It runs the start script via
// npm — npm ships with the node runtime image, so this works regardless of
// which package manager built the app (pnpm/yarn aren't in the runtime stage).
// With no start script it runs node on the entrypoint directly.
func nodeStart(pkg nodePkg) string {
	if pkg.Scripts["start"] != "" {
		return jsonArr([]string{"npm", "run", "start"})
	}
	main := pkg.Main
	if main == "" {
		main = "index.js"
	}
	return jsonArr([]string{"node", main})
}

func jsonArr(parts []string) string {
	b, _ := json.Marshal(parts)
	return string(b)
}
