package builder

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// Node generates a lean multi-stage Dockerfile for npm/pnpm/yarn projects.
// Bun projects (bun.lockb) are left to Nixpacks since they need the bun runtime.
type Node struct{}

func (Node) Name() string { return "node" }

func exists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func (Node) Match(dir string) bool {
	return exists(filepath.Join(dir, "package.json")) && !exists(filepath.Join(dir, "bun.lockb"))
}

type nodePkg struct {
	Scripts        map[string]string `json:"scripts"`
	Main           string            `json:"main"`
	PackageManager string            `json:"packageManager"`
	Engines        struct {
		Node string `json:"node"`
	} `json:"engines"`
}

// pmSpec describes how to drive one package manager inside the Dockerfile.
type pmSpec struct {
	corepack   bool
	lockFile   string   // "" if none present
	install    string   // full install command
	runv       []string // script runner prefix, e.g. ["pnpm","run"]
	prune      string   // "" to skip (keep all deps)
	cacheMount string   // BuildKit cache mount for the package store, or ""
}

var nodeMajorRe = regexp.MustCompile(`\d+`)

func (Node) Dockerfile(dir string) (string, error) {
	raw, err := os.ReadFile(filepath.Join(dir, "package.json"))
	if err != nil {
		return "", err
	}
	var pkg nodePkg
	if err := json.Unmarshal(raw, &pkg); err != nil {
		return "", fmt.Errorf("parse package.json: %w", err)
	}

	nodeVer := "22"
	if m := nodeMajorRe.FindString(pkg.Engines.Node); m != "" {
		nodeVer = m
	}
	pm := detectPM(dir)
	hasBuild := pkg.Scripts["build"] != ""

	var b strings.Builder
	b.WriteString("# syntax=docker/dockerfile:1\n")
	b.WriteString("# generated by Cargo — lean multi-stage Node build\n")

	// ---- build stage ----
	fmt.Fprintf(&b, "FROM node:%s-alpine AS build\n", nodeVer)
	b.WriteString("WORKDIR /app\n")
	if pm.corepack {
		b.WriteString("RUN corepack enable\n")
	}
	if pm.lockFile != "" {
		fmt.Fprintf(&b, "COPY package.json %s ./\n", pm.lockFile)
	} else {
		b.WriteString("COPY package.json ./\n")
	}
	if pm.cacheMount != "" {
		fmt.Fprintf(&b, "RUN %s %s\n", pm.cacheMount, pm.install)
	} else {
		fmt.Fprintf(&b, "RUN %s\n", pm.install)
	}
	b.WriteString("COPY . .\n")
	if hasBuild {
		fmt.Fprintf(&b, "RUN %s build\n", strings.Join(pm.runv, " "))
	}
	if pm.prune != "" {
		fmt.Fprintf(&b, "RUN %s\n", pm.prune)
	}

	// ---- runtime stage (only prod deps + built output) ----
	fmt.Fprintf(&b, "\nFROM node:%s-alpine AS run\n", nodeVer)
	b.WriteString("WORKDIR /app\n")
	b.WriteString("ENV NODE_ENV=production\n")
	b.WriteString("RUN addgroup -S app && adduser -S app -G app\n")
	b.WriteString("COPY --from=build --chown=app:app /app ./\n")
	b.WriteString("USER app\n")
	fmt.Fprintf(&b, "CMD %s\n", nodeStart(pkg, pm))
	return b.String(), nil
}

// detectPM picks the package manager from the lockfiles present.
func detectPM(dir string) pmSpec {
	switch {
	case exists(filepath.Join(dir, "pnpm-lock.yaml")):
		return pmSpec{
			corepack:   true,
			lockFile:   "pnpm-lock.yaml",
			install:    "pnpm install --frozen-lockfile",
			runv:       []string{"pnpm", "run"},
			prune:      "pnpm prune --prod",
			cacheMount: "--mount=type=cache,target=/root/.local/share/pnpm/store",
		}
	case exists(filepath.Join(dir, "yarn.lock")):
		// Plain `yarn install` works across yarn classic and berry; pruning
		// differs between them, so keep all deps (correctness over a smaller
		// image) — still far leaner than Nixpacks.
		return pmSpec{
			corepack:   true,
			lockFile:   "yarn.lock",
			install:    "yarn install --frozen-lockfile",
			runv:       []string{"yarn", "run"},
			cacheMount: "--mount=type=cache,target=/usr/local/share/.cache/yarn",
		}
	case exists(filepath.Join(dir, "package-lock.json")):
		return pmSpec{
			lockFile:   "package-lock.json",
			install:    "npm ci",
			runv:       []string{"npm", "run"},
			prune:      "npm prune --omit=dev",
			cacheMount: "--mount=type=cache,target=/root/.npm",
		}
	default: // no lockfile
		return pmSpec{
			install:    "npm install",
			runv:       []string{"npm", "run"},
			prune:      "npm prune --omit=dev",
			cacheMount: "--mount=type=cache,target=/root/.npm",
		}
	}
}

// nodeStart returns the CMD (JSON exec form): the start script if defined,
// else `node <main|index.js>`.
func nodeStart(pkg nodePkg, pm pmSpec) string {
	if pkg.Scripts["start"] != "" {
		return jsonArr(append(append([]string{}, pm.runv...), "start"))
	}
	main := pkg.Main
	if main == "" {
		main = "index.js"
	}
	return jsonArr([]string{"node", main})
}

func jsonArr(parts []string) string {
	b, _ := json.Marshal(parts)
	return string(b)
}
